compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@commitlint/cli@*":
    peerDependencies:
      typescript: ">=4.9.5"
  "@commitlint/load@*":
    peerDependencies:
      "@types/node": "*"
      typescript: ">=4.9.5"
  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: ">=4.2.0"

pnpEnableEsmLoader: true
