compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@commitlint/cli@*":
    peerDependencies:
      typescript: ">=4.9.5"
  "@commitlint/load@*":
    peerDependencies:
      "@types/node": "*"
      typescript: ">=4.9.5"
  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: ">=4.2.0"
  "@typescript-eslint/type-utils@*":
    peerDependencies:
      eslint: ^8.57.0 || ^9.0.0
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint-plugin-import: ">=2.25.2"

pnpEnableEsmLoader: true
